/*
 * Creado el 03-jul-06
 *
 * Para cambiar la plantilla para este archivo generado vaya a
 * Ventana&gt;Preferencias&gt;Java&gt;Generaciï¿½n de cï¿½digo&gt;Cï¿½digo y comentarios
 */
package com.vendenet.utilidades.constantes;



/**
 * @author TXUS
 *
 * Para cambiar la plantilla para este comentario de tipo generado vaya a
 * Ventana&gt;Preferencias&gt;Java&gt;Generaciï¿½n de cï¿½digo&gt;Cï¿½digo y comentarios
 */
public final class TextConstant {
	
	public static String WATERMARK = ConstantesVendenet.RUTA_IMAGENES+"watermark.png";
	public static String _URL_BASE = "http://www.vendenet.net/vendenet/";
	public static String _URL_DARSE_DE_BAJA = _URL_BASE+"ServletControlador?accion=darseDeBaja";
	public static String _URL_MODIFICAR_ANUNCIO = _URL_BASE+"ServletControlador?accion=modificarAnuncio&idAnuncio=";
	public static String _URL_VER_ANUNCIO = _URL_BASE+"ServletControlador?accion=verAnuncio&idAnuncio=";
	public static String _URL_CONFIRMAR_OPINION = _URL_BASE+"ServletControlador?accion=confirmarOpinion&codigo=";
	public static String ACTION_BORRAR_ANUNCIO = "borrarAnuncio";
	public static String ACTION_MODIFICAR_ANUNCIO = "modificarAnuncio";
	public static String ALMOHADILLA = "~";
	public static String ANUNCIOS = "anuncios";
	public static String ANUNCIO_ACEPTADO = "Tu anuncio ha sido aceptado en vendenet";
	public static String ANUNCIO_ACEPTADO_VENDENET = "Anuncio aceptado por Vendenet";
	public static String ANUNCIO_BORRADO = "Tu anuncio ha sido borrado de vendenet";
	public static String ANUNCIO_EN_REVISION = "ANUNCIO EN REVISI&Oacute;N";
	public static String ANUNCIO_EN_REVISION_INFORMA1 = "Gracias por confiar en Vendenet. ";
	public static String ANUNCIO_EN_REVISION_INFORMA2 = "Tu anuncio ha entrado en el proceso de revisi&oacute;n y ser&aacute; publicado cuanto antes.";
	public static String ANUNCIO_NOTIFICACION_BORRADO = "Se ha borrado un anuncio";
	public static String ANUNCIO_NOTIFICACION_MODIFICADO = "Se ha modificado un anuncio, revision pendiente";
	public static String ANUNCIO_NO_ACEPTADO = "Tu anuncio no cumple alguna de las condiciones de publicación de vendenet.";
	public static String ANUNCIO_NO_ENCONTRADO = "Este anuncio ha caducado en Vendenet o no existe.";
	public static String ANUNCIO_NOTIFICACION_NUEVO = "Se ha registrado un nuevo anuncio";
	public static String ANUNCIOS_CLIENTE = "<div style='color:#666;font-size: 0.8em;'>(Vendedor $0)&nbsp;Anuncios publicados&nbsp;<spam style='color:white;'>$1</spam></div>";
	public static String ANUNCIOS_POR_REVISAR = "Anuncios por revisar: ";
	public static String ANYADE_ANUNCIO_RED_SOCIAL = "A&Ntilde;ADE ESTE ANUNCIO A TU RED SOCIAL";
	public static String APERTURA_A_DARK_OK = "<a href='javascript:despublicar();'>";
	public static String APERTURA_A_OK = "<a href='javascript:aceptar();'>";
	public static String APERTURA_A_KO = "<a href='javascript:denegarKo();'>";
	public static String APERTURA_A_WRN = "<a href='javascript:denegarWrn();'>";
	public static String APERTURA_DIV = "<div>";
	public static String APERTURA_DIV_CAMPO_CAMPO_ANUNCIO = "<div class='campo_campo_anuncio'>";
	public static String APERTURA_DIV_CAMPO_CAMPO_FORMULARIO = "<div class='campo_campo_formulario'>";
	public static String APERTURA_DIV_CAMPO_CONTACTO_MAIL_ANUNCIO_A = "<div class='campo_campo_contacto_mail_anuncio_a'>";
	public static String APERTURA_DIV_CAMPO_CONTACTO_MAIL_ANUNCIO_B = "<div id='capaOculta_mail' class='campo_campo_contacto_mail_anuncio_b'>";
	public static String APERTURA_DIV_CAMPO_CONTACTO_TFNO_ANUNCIO_A = "<div class='campo_campo_contacto_tfno_anuncio_a'>";
	public static String APERTURA_DIV_CAMPO_CONTACTO_TFNO_ANUNCIO_B = "<div id='capaOculta_telefono' class='campo_campo_contacto_tfno_anuncio_b'>";
	public static String APERTURA_DIV_CAMPO_FECHA_HORA_ANUNCIO = "<div class='campo_fecha_hora_anuncio'>";
	public static String APERTURA_DIV_CAMPO_LABEL_FORMULARIO = "<div class='campo_label_formulario'>";
	public static String APERTURA_DIV_CAMPO_LABEL_FORMULARIO_LARGO = "<div class='campo_label_formulario_largo'>";
	public static String APERTURA_DIV_CAMPO_LABEL_GRIS = "<div class='campo_label_gris'>";
	public static String APERTURA_DIV_CAMPO_PRECIO_ANUNCIO = "<div class='campo_precio_anuncio'>";
	public static String APERTURA_DIV_CAMPO_TEXTO_ANUNCIO = "<div class='campo_texto_anuncio'>";
	public static String APERTURA_DIV_CAMPO_TITULO_ANUNCIO = "<div class='campo_titulo_anuncio'>";
	public static String APERTURA_DIV_CAMPO_TEXTO_BLANCO_ANUNCIO = "<div class='campo_texto_blanco_anuncio'>";
	public static String APERTURA_DIV_CAMPO_TEXTO_BLANCO_AREA_GESTION = "<div class='campo_texto_blanco_area_gestion'>";
	public static String APERTURA_DIV_CAMPO_VISITAS_ANUNCIO = "<div class='campo_visitas_anuncio'>";
	public static String APERTURA_DIV_CAMPO_VOLVER_ANUNCIO = "<div class=\"campo_volver_anuncio\" onclick=\"javascript:history.back()\">";
	public static String APERTURA_DIV_CAMPO_VOLVER_RESULTADOS = "<div class='campo_volver_resultados'>";
	public static String APERTURA_DIV_CENTRADO = "<div class='centrado'>";
	public static String APERTURA_DIV_CENTRADO_SIN_MARGEN = "<div class='centrado_sin_margen'>";
	public static String APERTURA_DIV_CENTRADO_LIMPIO = "<div class='centrado_limpio'>";
	public static String APERTURA_DIV_CENTRADO_DERECHA = "<div class='derecha'>";
	public static String APERTURA_DIV_CENTRADO_DERECHA_NEGRITA = "<div class='derecha_negrita'>";
	public static String APERTURA_DIV_CENTRADO_DERECHA_REPUTACION = "<div class='derecha_reputacion'>";
	public static String APERTURA_DIV_CENTRADO_IZQUIERDA = "<div class='izquierda'>";
	public static String APERTURA_DIV_CENTRADO_IZQUIERDA_NEGRITA = "<div class='izquierda_negrita'>";
	public static String APERTURA_DIV_CABECERA_RESULTADOS = "<div class='cabecera_resultados'>";
	public static String APERTURA_DIV_CAPA_PRELIMINAR_ANUNCIO = "<div class='capa_preliminar_anuncio'>";
	public static String APERTURA_DIV_CAPA_FICHA_ANUNCIO = "<div class='capa_ficha_anuncio'>";
	public static String APERTURA_DIV_CAPA_FONDO_SOMBREADO = "<div class='capa_fondo_sombreado'>";
	public static String APERTURA_DIV_CIEN = "<div class='cien'>";
	public static String APERTURA_DIV_CINCUENTA = "<div class='cincuenta'>";
	public static String APERTURA_DIV_CUARENTA_Y_CINCO_MARGEN_IZQUIERDA = "<div class='cuarenta_y_cinco_margen_izquierda'>";
	public static String APERTURA_DIV_CUARENTA_Y_CINCO_MARGEN_DERECHA = "<div class='cuarenta_y_cinco_margen_derecha'>";
	public static String APERTURA_DIV_CUARTO_FLOAT = "<div class='cuarto_float'>";
	public static String APERTURA_DIV_DIEZ = "<div class='diez'>";
	public static String APERTURA_DIV_DIEZ_MARGEN_IZQUIERDA = "<div class='diez_margen_izquierda'>";
	public static String APERTURA_DIV_ESTRELLITAS = "<div class='estrellitas'>";
	public static String APERTURA_DIV_FLOAT_LEFT = "<div class='left'>";
	public static String APERTURA_DIV_FLOAT_LEFT_TOP = "<div class='left_top'>";
	public static String APERTURA_DIV_FLOAT_RIGHT = "<div class='right'>";
	public static String APERTURA_DIV_GRIS_MARGEN_INFERIOR = "<div class='gris_margen_inferior'>";
	public static String APERTURA_DIV_IMAGEN_LOADING = "<div align='center' class='imagen_loading'>";
	public static String APERTURA_DIV_LOGO = "<div align='center' class='logo'>";
	public static String APERTURA_DIV_LOGO_DOMINIO = "<div align='center' class='logo_dominio'>";
	public static String APERTURA_DIV_LOGO_TEXTO = "<div align='center' class='logo_texto'>";
	public static String APERTURA_DIV_LOGO_PUNTO = "<div align='center' class='logo_punto'>";
	public static String APERTURA_DIV_MARGEN_INFERIOR = "<div class='margen_inferior'>";
	public static String APERTURA_DIV_NOVENTA_MARGEN_DERECHA_IZQUIERDA = "<div class='noventa_margen_derecha_izquierda'>";
	public static String APERTURA_DIV_NOVENTA_MARGEN_DERECHA_DERECHA = "<div class='noventa_margen_derecha_derecha'>";
	public static String APERTURA_DIV_QUINCE = "<div class='quince'>";
	public static String APERTURA_DIV_RESULTADOS = "<div class='resultados'>";
	public static String APERTURA_DIV_SESENTA = "<div class='sesenta'>";
	public static String APERTURA_DIV_SESENTA_MARGEN_DERECHA = "<div class='sesenta_margen_derecha_peque'>";
	public static String APERTURA_DIV_SETENTA_MARGEN_DERECHA = "<div class='setenta_margen_derecha'>";
	public static String APERTURA_DIV_SETENTA_MARGEN_DERECHA_BLANCO = "<div class='setenta_margen_derecha_blanco'>";
	public static String APERTURA_DIV_SETENTA_MARGEN_DERECHA_PEQUE = "<div class='setenta_margen_derecha_peque'>";
	public static String APERTURA_DIV_SETENTA_MENSAJE_NO_REPUDIO = "<div class='setenta_mensaje_no_repudio'>";
	public static String APERTURA_DIV_SIN_RESULTADOS="<div class='sin_resultados'>";
	public static String APERTURA_DIV_TERCIO_FLOAT="<div class='tercio_float'>";
	public static String APERTURA_DIV_TREINTA = "<div class='treinta'>";
	public static String APERTURA_DIV_VEINTE = "<div class='veinte'>";
	public static String APERTURA_DIV_VEINTE_FLOAT = "<div class='veinte_float'>";
	public static String APERTURA_DIV_VEINTE_MARGEN_IZQUIERDA = "<div class='veinte_margen_izquierda'>";
	public static String APERTURA_DIV_VEINTE_MARGEN_IZQUIERDA_NEGRITA = "<div class='veinte_margen_izquierda_negrita'>";
	public static String APERTURA_LABEL = "<label>";
	public static String APERTURA_LABEL_OPINION = "<label id='label_opinion'>";
	public static String APERTURA_LABEL_ROJO = "<label class='rojo'>";
	public static String APERTURA_LABEL_NEGRITA = "<label class='negrita'>";
	public static String APERTURA_PARRAFO = "<p>";
	public static String AREA_GESTION = "&Aacute;rea de Gesti&oacute;n";
	public static String ASTERISCO = "(*)";
	public static String BAJA_REALIZADA_CORRECTAMENTE = "Baja realizada correctamente";
	public static String BLANK = "";	
	public static String BORRAR_ANUNCIO = "Borrar anuncio";
	public static String CATEGORIA = "Categoria";
	public static String CATEGORIA_GUION = "Categoria - ";
	public static String CERRAR_SESION = "Cerrar sesi&oacute;n";
	public static String CIERRE_A = "</a>";
	public static String CIERRE_DIV = "</div>";
	public static String CIERRE_LABEL = "</label>";
	public static String CIERRE_PARRAFO = "</p>";
	public static String CIUDADES = "Ciudades";
	public static String CONDICIONES = "CONDICIONES DE USO";
	public static String CONFIRMAR_ANUNCIO = "CONFIRMAR ANUNCIO";
	public static String CONFIRMAR_BAJA = "¿Est&aacute;s seguro que quieres borrar el email '$0' y su anuncio asociado?";
	public static String CONFIRMAR_CONTRASENA = "Repetir Clave";
	public static String CONFIRMAR_OPINION = "[VENDENET.NET] - Confirma tu opinion sobre el anunciante";
	public static String CONSULTA_ENVIADA = "Tu consulta se ha enviado al anunciante.";
	public static String CONSULTA_RECIBIDA = "[VENDENET.NET] - Hay un usuario de Vendenet interesado en tu anuncio ";
	public static String CONTACTA_POR_EMAIL = "Contacta por email";
	public static String CONTACTO = "<A HREF='mailto:info@vendenet.net'>info@vendenet.net</A>";
	public static String CONTRASENA = "Clave";
	public static String CONTRASENA_INCORRECTA = "Clave introducida incorrecta";
	public static String COMA = ", ";
	public static String COMA_HTML = "&#44;&nbsp;";
	public static String COPYRIGHT=new StringBuffer("&copy ").append(ConstantesVendenet.ANYO_ACTUAL).append(" vendenet.net, Reservados todos los derechos. ").append("<a href='ServletControlador?accion=condiciones'>Condiciones de uso.</a> - ") .append("<a href='ServletControlador?accion=contacto'>Contacto.</a>").toString();
	public static String CORCHO = "]";
	public static String CRITERIO_ORDEN_INTRANET = "fechaAlta";
	public static String CUERPO = "Cuerpo";
	public static String DEFAULT_CRITERIO_ORDEN = "fechaAlta";
	public static String DEVOLVER_ANUNCIO = "Devolver anuncio";
	public static String DOS_PUNTOS = ": ";
	public static String EMAIL = "Email";
	public static String EMAIL_DIV_ANUNCIO_ACEPTADO_1 = "<div style='margin-left: 2%; margin-top:3%; color: #666; font-family: Arial, Helvetica, sans-serif; font-size: 1em; font-weight: normal;'><div>Enhorabuena, tu anuncio ha sido aceptado en Vendenet!</div><div>Para ver tu anuncio pincha en el siguiente link</div><div><a href='";
	public static String EMAIL_DIV_ANUNCIO_ACEPTADO_2 = "'>";
	public static String EMAIL_DIV_ANUNCIO_DEVUELTO_1 = "<div style='margin-left: 2%; margin-top:3%; color: #666; font-family: Arial, Helvetica, sans-serif; font-size: 1em; font-weight: normal;'><div>Lo sentimos, tu anuncio no cumple con las normas de Vendenet, el motivo es el siguiente:</div><div style='color: red;'>";
	public static String EMAIL_DIV_ANUNCIO_DEVUELTO_2 = "</div><div>Para modificar el anuncio pulse ";
	public static String EMAIL_DIV_CONFIRMAR_OPINION = "<div style='margin-left: 2%; margin-top:3%; color: #666; font-family: Arial, Helvetica, sans-serif; font-size: 1em; font-weight: normal;'><div>Hola $0, has registrado una opinion sobre un anunciante en Vendenet.net. Para confirmar tu opinion pincha en el siguiente link</div><div><a href='";
	public static String EMAIL_DIV_CONSULTA_1 = "<div style='margin-left: 2%; margin-top:3%; color: #666; font-family: Arial, Helvetica, sans-serif; font-size: 1em; font-weight: normal;'><div>Hay un usuario de Vendenet interesado en tu anuncio, estos son sus datos:</div>";
	public static String EMAIL_DIV_CONSULTA_2 = "<div>Nombre: <strong>";
	public static String EMAIL_DIV_CONSULTA_3 = "</strong></div>";
	public static String EMAIL_DIV_CONSULTA_4 = "<div>Telefono: <strong>";
	public static String EMAIL_DIV_CONSULTA_5 = "<div>Email de contacto: <strong>";
	public static String EMAIL_DIV_CONSULTA_6 = "<div>Y su consulta es la siguiente:</div><div style='margin-top:2%; margin-bottom:2%; color: red'>";
	public static String EMAIL_DIV_CONSULTA_7 = "<div>Para ver tu anuncio pincha en el siguiente link</div><div><a href='"+_URL_VER_ANUNCIO;
	public static String EMAIL_DIV_CONSULTA_8 = "'>";
	public static String EMAIL_DIV_RECORDATORIO_1 = "<div style='margin-left: 2%; margin-top:3%; margin-bottom:1%; color: #666; font-family: Arial, Helvetica, sans-serif; font-size: 1em; font-weight: normal;'><div>Se ha solicitado la contrase&ntilde;a desde el portal de vendenet.net:</div>";
	public static String EMAIL_DIV_RECORDATORIO_2 = "<div style='margin-top:2%; margin-bottom:2%; '>Tu contrase&ntilde;a es:<span style='color: red'>";
	public static String EMAIL_DIV_RECORDATORIO_3 = "</span></div>";
	public static String EMAIL_VENDENET = "info@vendenet.net";
	public static String ERROR = "Error";
	public static String ESTADISTICAS = "Estadisticas Vendenet";
	public static String FECHA = "Fecha";
	public static String FECHA_ADJUNTO = "fecha";
	public static String FECHA_ALTA = "fechaAlta";
	public static String FECHA_CADUCIDAD = "fechaCaducidad";
	public static String FLECHA_ABAJO = "imagenes/flecha_abajo.gif";
	public static String FLECHA_ABAJO_GRIS = "imagenes/flecha_abajo_gris.gif";
	public static String FLECHA_ARRIBA = "imagenes/flecha_arriba.gif";
	public static String FLECHA_ARRIBA_GRIS = "imagenes/flecha_arriba_gris.gif";
	public static String FORMATO_INVALIDO = "Formato de imagen incorrecto, elija por favor otra imagen.";
	public static String FOTOGRAFIA = "Fotograf&iacute;a";
	public static String GUION_BAJO = "_";
	public static String HISTORICO_BAJAS = "Hist&oacute;rico bajas";
	public static String HISTORICO_BUSQUEDAS = "Hist&oacute;rico b&uacute;squedas";
	public static String HISTORICO_EMAILS = "Hist&oacute;rico email";
	public static String HOY = "Hoy";
	public static String HTMLBLANK = "&nbsp;";
	public static String HTMLTHREEBLANK = "&nbsp;&nbsp;&nbsp;";
	public static String HTML_TRADEMARK = "&#8482;";
	public static String HTML_CRUZ = "&#8224;";
	public static String HTML_CRUZ_DOBLE = "&#8225;";
	public static String HTML_INTEGRAL = "&#402;";
	public static String HTML_COMUNIDAD_EUROPEA = "&#338;";
	public static String HTML_CERRAR_COMITAS = "&#8221;";
	public static String HTML_EURO = "&#8364;";
	public static String HTML_ABRIR_COMITAS = "&#8220;";
	public static String HTML_PORCIENTO_RARO = "&#8240;";
	public static String HTML_SALTO_LINEA = "<BR/>";
	public static String ID_CRITERIO_ORDEN_FECHA = "1";
	public static String IMAGEN_EMAIL = "<A HREF='mailto:info@vendenet.net'><img width='100' height='100' src='imagenes/email.png'/></A>";
	public static String IMAGEN_DARK_OK_P = "<img src='imagenes/p_dark_ok.png'/>";
	public static String IMAGEN_FACEBOOK = "<img src='imagenes/facebook.png'/>";
	public static String IMAGEN_FONDO = "Fondo.jpg";
	public static String IMAGEN_HALF_STAR = "half_star.png";
	public static String IMAGEN_HALF_STAR_YELLOW= "yellow_half_star.png";
	public static String IMAGEN_HALF_STAR_RED= "red_half_star.png";
	public static String IMAGEN_HALF_STAR_GREEN= "green_half_star.png";
	public static String IMAGEN_KO = "<img src='imagenes/ko.png'/>";
	public static String IMAGEN_OK = "<img src='imagenes/p_ok.png'/>";
	public static String IMAGEN_WRN = "<img src='imagenes/wrn.png'/>";
	public static String IMAGEN_KO_P = "<img src='imagenes/p_ko.png'/>";
	public static String IMAGEN_KO_I = "i_ko.png";
	public static String IMAGEN_OK_P = "<img src='imagenes/p_ok.png'/>";
	public static String IMAGEN_WRN_P = "<img src='imagenes/p_wrn.png'/>";
	public static String IMAGEN_PUNTO = "<img class='punto' src='imagenes/i_ko.png'/>";
	public static String IMAGEN_STAR_YELLOW = "yellow_star.png";
	public static String IMAGEN_STAR_RED = "red_star.png";
	public static String IMAGEN_STAR_GREEN = "green_star.png";
	public static String IMAGEN_STAR_GREY = "grey_star.png";
	public static String IMAGEN_TWITTER = "<img src='imagenes/twitter.png'/>";
	public static String INCLUIR_PUBLICADOS = "Incluir Publ.";
	public static String INCLUIR_REVISADOS = "Incluir Revis.";
	public static String INICIO = "inicio";
	public static String INSERTAR_ANUNCIO = "INSERTAR ANUNCIO.";
	public static String IP_VACIA = "Ip vacia";
	public static String KEY_ACCION = "accion";
	public static String KEY_ANUNCIO = "anuncio";
	public static String KEY_CATEGORIA = "idCategoria";
	public static String KEY_CITYREGISTRED = "cityregistred";
	public static String KEY_CIUDADES_TEMP = "KEY_CIUDADES_TEMP";
	public static String KEY_CITYNAME = "cityName";
	public static String KEY_REGIONNAME = "regionName";
	public static String KEY_CLIENTE = "cliente";
	public static String KEY_CRITERIO_ORDEN = "idCriterioOrden";
	public static String KEY_CRITERIOS_ORDEN = "lstCriteriosOrden";
	public static String KEY_EMAIL = "email";
	public static String KEY_ENVIOS_REALIZADOS = "enviosRealizados";
	public static String KEY_FECHA_DESDE = "fechaDesde";
	public static String KEY_FECHA_HASTA = "fechaHasta";
	public static String KEY_HISTORICO_BORRADOS = "historicoBorrados";
	public static String KEY_HISTORICO_BUSQUEDAS = "KEY_HISTORICO_BUSQUEDAS";
	public static String KEY_ICONO = "icono";
	public static String KEY_IPHONE = "iphone";
	public static String KEY_INCLUIR_PUBLICADOS = "incluir_publicados";
	public static String KEY_INCLUIR_REVISADOS = "incluir_revisados";
	public static String KEY_LISTA_ANUNCIOS_SIN_PUBLICAR = "listado_anuncios_por_publicar";
	public static String KEY_LISTA_CRITICAS = "KEY_LISTA_CRITICAS";
	public static String KEY_MENSAJE = "KEY_MENSAJE";
	public static String KEY_NAVEGADORES_BOT = "________________________________________________________";
	public static String KEY_NOMBRE = "nombre";
	public static String KEY_NUM_TOTAL = "numTotal";
	public static String KEY_NUM_TOTAL_ANUNCIOS_REVISION = "numTotalAnunciosRevision";
	public static String KEY_PAGINA_ACTUAL = "paginaActual";
	public static String KEY_PROVINCIA = "idProvincia";
	public static String KEY_RESPUESTA = "respuesta";
	public static String KEY_TIPO_ANUNCIO = "tipoAnuncio";
	public static String KEY_TIPO_VENDEDOR = "tipoVendedor";
	public static String KEY_USUARIO = "usuario";
	public static String KEY_PROVINCIAS = "lstProvincias";
	public static String KEY_CATEGORIAS = "lstCategorias";
	public static String KEY_TIPOS_VENDEDOR = "lstTiposVendedor";
	public static String KEY_TIPOS_ANUNCIO = "lstTiposAnuncio";
	public static String KEY_TIPOS_NAVEGADOR = "tiposNavegador";
	public static String KEY_TOTAL_ANUNCIOS = "KEY_TOTAL_ANUNCIOS";
	public static String KEY_TOTAL_VISITAS = "visitasTotal";
	public static String KEY_VISITA_REGISTRADA = "keyVisitaRegistrada";
	public static String KEY_VISITAS_INTRANET = "keyVisitasIntranet";
	public static String KEY_VISITAS_WEB = "keyVisitasWeb";
	public static String LLAMA_A = "Llama a ";
	public static String LINK_GOOGLE_PLUS = "<g:plusone size=\"medium\"></g:plusone>";
	public static String MENSAJE_AYUDA_BUSCAR_HMTL = "Ejemplo: BMW M3 clima abs libro revisiones...<br>Consejo: Acota las b&uacute;squedas por provincia y categor&iacute;a";
	public static String MENSAJE_AYUDA_BUSCAR = "Ejemplo: BMW M3 clima abs libro revisiones...Consejo: Acota las b&uacute;squedas por provincia y categor&iacute;a";
	public static String MENSAJE_ERROR = "Ha habido un error intentalo en unos minutos";
	public static String MENSAJE_DEPLAZAMIENTO_PROVINCIA_IPHONE = "En el iphone/ipad para deslizar hacia abajo en las provincias, con dos dedos a la vez";
	public static String MENSAJE_DEPLAZAMIENTO_CATEGORIA_IPHONE = "En el iphone/ipad para deslizar hacia abajo en las categorias, con dos dedos a la vez";
	public static String MENSAJE_OPINION_CONFIRMADA = "Gracias por utilizar Vendenet. <BR/> Se ha confirmado tu opini&oacute;n, el resto de usuarios podr&aacute;n ver tu opini&oacute;n sobre este anunciante";
	public static String MENSAJE_OPINION_YA_CONFIRMADA = "Gracias por utilizar Vendenet. <BR/> La opinion correspondiente a ese c&oacute;digo ya esta confirmada";
	public static String MENSAJE_OPINION_NO_CONFIRMADA = "Lo sentimos no se ha podido confirmar una opini&oacute;n con ese c&oacute;digo";
	public static String MODIFICAR_ANUNCIO = "Modificar anuncio";
	public static String NAVEGADOR_DESCONOCIDO = "Navegador desconocido/vacio";
	public static String NAVEGADORES_RECOMENDADOS_A = new StringBuffer("Para una &oacute;ptima visualizaci&oacute;n,Vendenet recomienda").toString();
	public static String NAVEGADORES_RECOMENDADOS_B = new StringBuffer("<a href=javascript:abrirUrl('http://www.mozilla-europe.org/es/')><img src='imagenes/firefox.gif'/></a>")
	.append("<a href=javascript:abrirUrl('http://www.google.com/chrome?hl=es')><img src='imagenes/chrome.png'/></a>")
	.append("<a href=javascript:abrirUrl('http://www.opera.com/download/get.pl?id=33787&thanks=true&sub=true')><img src='imagenes/opera.png'/></a>")
	.append("<a href=javascript:abrirUrl('http://www.apple.com/es/safari/download/')><img src='imagenes/safari.jpg'/></a>").toString();
	public static String NO_SE_HA_PODIDO_DAR_DE_BAJA = "No se ha podido realizar la baja.";
	public static String NO_SE_HA_PODIDO_DAR_DE_BAJA_ERROR = "Sentimos las molestias. No se ha podido realizar la baja. Si lo desea, envie un email a info@vendenet.net y tramitaremos personalmente.";
	public static String NOMBRE = "Nombre";
	public static String NUMERO_DE_ANUNCIO_INCORRECTO = "Numero de anuncio incorrecto";
	public static String OCULTAR_TODOS = "Ocultar todos";
	public static String OK = "OK";
	public static String OPINA_SOBRE_VENDEDOR = "<div class='opina_vendedor'><a href='$0'>Lee y opina sobre este anunciante</a></div>";
	public static String OPINION_ANUNCIANTE = "Tu valoraci&oacute;n";
	public static String OPINION_REGISTRADA = "Se ha registrado tu opini&oacute;n, se te enviar&aacute; un email durante los pr&oacute;ximos 5 minutos para que confirmes tu valoraci&oacute;n del anunciante";
	public static String ORDENADOR_POR_GUION = "Ordenado por - ";
	public static String PARENTESIS_ABRIR= "(";
	public static String PARENTESIS_CERRAR= ")";
	public static String PATRON= "patron";
	public static String PATRON_NO_AJAX= "patron_no_ajax";
	public static String PLANTILLA_EMAIL_PRE= "";
	public static String PLANTILLA_EMAIL_POST= "";
	public static String PONER_OPINION = "OPINIONES EN DETALLE";
	public static String PREGUNTA= "Pregunta";
	public static String PRE_FOTO_ICONO = "i_";
	public static String PRE_FOTO_PEQUE = "p_";
	public static String PRE_FOTO_MAX = "g_";
	public static String PRECIO = "	Precio";
	public static String PROVINCIA = "Provincia";
	public static String PUBLICAR_ANUNCIO = "Publicar anuncio";
	public static String PUNTOS_SUSPENSIVOS = "...";
	public static String PUNTO = ".";
	public static String REVISAR_CAMPOS_ROJOS = "Revisa los campos en rojo para continuar (incluyendo el menu de la izquierda)";
	public static String REVISAR_CAMPOS_ROJOS_OPINION = "Revisa los campos en rojo para continuar";
	public static String REVISA_EL_ANUNCIO = "Revisa tus datos antes de publicar el anuncio.";
	public static String FLAG_NO_PUBLICADO = "(*)";
	public static String FLAG_REVISION = "(*)";
	public static String PALABRAS_MAL_SONANTES = "Palabras malsonantes o prohibidas en el anuncio.";
	public static String RADIO_ELIMINAR_SELECCIONADO = "<input id='radioeliminar' type='radio' name='radiogestion' value='0' checked='checked'/><label for='radioeliminar'>Eliminar anuncio</label>";
	public static String RADIO_ELIMINAR = "<input id='radioeliminar' type='radio' name='radiogestion' value='0'/><label for='radioeliminar'>Eliminar anuncio</label>";
	public static String RADIO_MODIFICAR = "<input id='radiomodificar' type='radio' name='radiogestion' value='1'/><label for='radiomodificar'>Modificar anuncio</label>";
	public static String RADIO_MODIFICAR_SELECCIONADO = "<input id='radiomodificar' type='radio' name='radiogestion' value='1' checked='checked'/><label for='radiomodificar'>Modificar anuncio</label>";
	public static String RESULTADOS = "resultados";
	public static String REVISION_ANUNCIOS = "Revisi&oacute;n de anuncios";
	public static String SALTO_LINEA = "\r";
	public static String SE_HAN_ENCONTRADO = "Se han encontrado ";
	public static String SESION_CADUCADA = "Sesion caducada";
	public static String SIGUENOS_EN = "&nbsp;&nbsp;";
	
	public static String SIN_FOTO_PEQUE="p_0.jpg";
	public static String SIN_FOTO_ICONO="i_0.jpg";
	public static String SIN_FOTO="0.jpg";
	public static String SIN_OPINIONES="Este anunciante aun no tiene opiniones";
	public static String SIN_RESULTADOS="Lo sentimos, no se han encontrado resultados para esta b&uacute;squeda";
	public static String SLASH = "/";
	public static String SPACE = " ";
	public static String MENSAJE_NO_SPAM = "Con el fin de protegerte del correo spam, tu email no estar&aacute; visible en el anuncio. Los usuarios solo podr&aacute;n contactar a trav&eacute;s de un formulario.";
	public static String MENSAJE_NO_REPUDIO = "Se enviar&aacute; un correo a la direcci&oacute;n indicada y se solicitar&aacute; confirmaci&oacute;n de publicaci&oacute;n de la opini&oacute;n.";
	public static String STRING_TRUE = "true";
	public static String TAMANYO_FOTO_SUPERADO = "La foto no puede superar los 10 megas, elija por favor otra imagen.";
	public static String TIPO_VENDEDOR = "Tipo de vendedor";
	public static String KEY_TELEFONO = "telefono";
	public static String TEXTO_ANUNCIO = "Texto anuncio";
	public static String TEXTO_OPINION = "Texto opini&oacute;n";
	public static String TFNO = "Tel&eacute;fono";
	public static String TIENES_OPINIONES_PENDIENTES = "Lo sentimos, tienes una opinion pendiente de confirmar, revisa por favor tu correo.";
	public static String TIENES_MUCHAS_OPINIONES = "Lo sentimos, has excedido del numero de opiniones para el mismo vendedor";
	public static String TIPO_EMAIL_RECORDATORIO = "Solicitud de clave Vendenet.net";
	public static String TIPO_ANUNCIO = "Tipo de anuncio";
	public static String TIPO_ANUNCIO_GUION = "Tipo de anuncio - ";
	public static String TIPO_VENDEDOR_GUION = "Tipo de vendedor - ";
	public static String TITULO = "T&iacute;tulo";
	public static String TODAS = "Todas";
	public static String TODOS = "Todos";
	public static String TOTAL_VISITAS = "Total visitas : ";
	public static String URL_COMPARTIR_TWITTER = "http://twitter.com/intent/tweet?source=webclient&text=";
	public static String URL_COMPARTIR_FACEBOOK = "http://www.facebook.com/sharer/sharer.php?u=";
	public static String URL_FACEBOOK = "javascript:abrirUrl('http://www.facebook.com/pages/Vendenet/229612917054553?sk=wall')";
	
//	public static String URL_INICIO = "/vendenet/ServletControlador?accion=inicio&subAccion=inicio";
	public static String URL_INICIO = "http://www.vendenet.net";
	public static String URL_TWITTER = "javascript:abrirUrl('http://twitter.com/#!/vendenet')";
	public static String URL_VENDENET_VERANUNCIO = "http://www.vendenet.net/vendenet/ServletControlador?accion=";
	
	public static String USER_AGENT = "user-agent";
	public static String VENDENET = "Vendenet";
	public static String VER_ANUNCIO = "Ver anuncio";
	public static String VER_EMAIL = "Ver/Ocultar";
	public static String VISITAS = "Visitas";
	public static String VISUALIZAR_DATOS_ANUNCIANTE = "Mostrar datos del anunciante";
	public static String VOLVER_AL_ANUNCIO = "Volver al anuncio";
	public static String VOLVER_A_LOS_RESULTADOS = "Volver a los resultados";
	public static String WEB_AMIGAS = "";
	public static String YA_HAY_UN_ENVIO_PENDIENTE = "Ya existe una solicitud de recordatorio de clave. Comprueba tu correo durante los siguientes minutos.";
	
	
	
	public TextConstant() {
		super();
		// TODO Apï¿½ndice de constructor generado automï¿½ticamente
	}

}